/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 情景模式拼音搜索列表开始滑动事件
 */
export const EVENT_ID_INTELLIGENCE_PINYIN_LIST_SCROLL_START: string = 'EVENT_ID_INTELLIGENCE_PINYIN_LIST_SCROLL_START';

export const EVENT_APP_LIST_LOAD_COMPLETE: string = 'appListLoadComplete';