/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// 正常等待时长
export const COMMON_DELAY: number = 1000;

// 等待组件最长时长
export const WAIT_DELAY: number = 2000;

// 正常等待时长
export const SWIPE_DELAY: number = 2000;

// 快速点击等待时长
export const QUICK_CLICK_DELAY: number = 500;

// AppFontManageTest 等待组件最长时长
export const APP_FONT_WAIT_DELAY: number = 2000;