/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 搜索结果中使用本地图标，而不是动态查询的图标应用列表
 */
export const FIXED_ICON_ENTRY_LIST: string[] = ['com.ohos.callsetting'];

/**
 * 通话设置应用使用固定图标
 */
export const FIXED_ICON_CALL_SETTINGS: string = 'com.ohos.callsetting';
