/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export { BrightnessController } from './src/main/ets/controller/BrightnessController';

export { SleepKey, SleepTime, SleepController } from './src/main/ets/controller/SleepController';

export {
  ScreenZoomController,
  SUMMARY_DEFAULT,
  SUMMARIES_SMALLER,
  SUMMARIES_LARGER
} from './src/main/ets/controller/ScreenZoomController';

export { FontSizeAdjustController } from './src/main/ets/controller/FontSizeAdjustController';

export { FontWeightAdjustController } from './src/main/ets/controller/FontWeightAdjustController';

export { DisplayUtils } from './src/main/ets/DisplayUtils';

export { DarkModePageController } from './src/main/ets/controller/darkmode/DarkModePageController';

export { TimeUtil } from './src/main/ets/utils/TimeUtil';
